services:
  kiii:
    image: marinojak/kiii:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://music_user:postgres@db:5432/music_publisher
    depends_on:
      db:
        condition: service_healthy  
    command: bash -c "python init_db.py && flask run --host=0.0.0.0"

  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: music_publisher
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_user"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
