apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-app-deploy
  namespace: kiii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-app
  template:
    metadata:
      labels:
        app: kiii-app
    spec:
      initContainers:
      - name: init-db
        image: marinojak/kiii:latest
        command: ["python", "init_db.py"]
        envFrom:
          - configMapRef:
              name: kiii-app-configmap
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database-url
      containers:
        - name: kiii-app
          image: marinojak/kiii:latest  
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: kiii-app-configmap
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-url
