apiVersion: v1
kind: Service
metadata:
  name: kiii-app-service
  namespace: kiii
spec:
  selector:
    app: kiii-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # type: LoadBalancer
