apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: kiii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: marinojak/kiii:latest  
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: FLASK_ENV
              value: development
            - name: FLASK_DEBUG
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-url

