apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-app-configmap
  namespace: kiii
data:
  FLASK_APP: app.py
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"
  FLASK_ENV: development
  FLASK_DEBUG: "1"